services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: mq-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: mq-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  # IBM MQ
  ibmmq:
    image: ibm-mqadvanced-server-dev:9.4.2.0-arm64
    platform: linux/arm64
    container_name: ibmmq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=passw0rd
    ports:
      - "1414:1414"   # Port IBM MQ (client)
      - "9443:9443"   # Port Web UI (admin console)
    volumes:
      - ibmmq-data:/mnt/mqm
    restart: unless-stopped  

  # Application Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mq-backend
    depends_on:
      postgres:
        condition: service_healthy
   #   ibmmq:
    #    condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mqmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_IBM_MQ_CONNNAME=ibmmq(1414)
      - SPRING_IBM_MQ_QUEUEMANAGER=QM1
      - SPRING_IBM_MQ_CHANNEL=DEV.ADMIN.SVRCONN
      - SPRING_IBM_MQ_USER=admin
      - SPRING_IBM_MQ_PASSWORD=passw0rd
    ports:
      - "8081:8081"

  # Frontend Angular
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: mq-frontend
#    depends_on:
#      - backend
#    ports:
#      - "4200:80"

volumes:
  postgres-data:
  ibmmq-data:
  pgadmin-data: